### ISSUE TITLE
AMD RX 4XX and 5XX Flat lit toon shaders invisible

### ISSUE THREAD

**Issue by Hopossum** [cubedparadox/Cubeds-Unity-Shaders#28] opened 2017-12-30 00:34 UTC
The RX 4XX and 5XX series of AMD GPU's is having an issue where in VR some of the shaders fail to render and make characters in VRchat and other games either invisible or a shadowed figure. I have tried installing older graphics drivers and the problem consists. I think the new update with how CUS renders is the cause of this issue.

**Comment by HammondParis** [comment] 2018-01-04 02:44
I am also having this issue as well. Shadows still cast onto the model, but the mesh is completely transparent. This has been an issue for over 2 months now.
![20171217023753_1](https://user-images.githubusercontent.com/35087201/34548300-507cb29a-f0cf-11e7-96db-2a0e245f818c.jpg)

**Comment by TCL987** [comment] 2018-01-07 06:06
Closing this as a duplicate of #27.

**Closed by TCL987** 2018-01-07 06:06 UTC
