### ISSUE TITLE
Chromatic image appears

### ISSUE THREAD

**Issue by joshthegrate** [cubedparadox/Cubeds-Unity-Shaders#46] opened 2018-06-24 19:05 UTC
I'm not sure what is going on but every now and then when I use an avatar with this shader applied I and those around me will get a ghostly chromatic image of my avatar usually upside down in there FOV and it will only go away if I switch to a avatar that is not using cubed shader. I have no idea what triggers it as it seems to be completely random and when it happens people instantly start blocking me without giving me a chance to change avatars.

**Comment by SonyUSA** [comment] 2018-06-25 07:16
The issue is the double-sided flat lit toon shader. When using single sided there are no chromatic ghosts, and the ghosts are typically just the meshes that it was applied to and not the entire model. Certain map lighting causes unbelievable eye strain BUT you can trigger it on any map by just opening your menu (as far as I could see). This is VRChat we are referring to.

**Comment by joshthegrate** [comment] 2018-06-25 19:04
Just switched all my avatars over to noenoe shader since it does the same thing I want from cubed and sofar no no issues from it. Thanks for pointing out what the culprit is. I kinda need double sided shading on some of my avatars to correct for missing textures on the inside of sleeves and such. Hope it gets worked out because I did see another player with the same issue last night when they where briefly in the same world as me.

**Comment by SonyUSA** [comment] 2018-06-25 19:41
If you're in a pinch you can add an outline with a 0 pixel width then choose a "close enough" color from the color wheel for the "inside" of a texture. Works with any single sided shader.

**Comment by lyuma** [comment] 2018-07-20 05:32
For all the shaders (except the classic non-Lite version) you have to edit the shader and find #include "FlatLitToonCore.cginc" and replace with "FlatLitToonCoreLite.cginc". This fixed it for me.

The issue is in more detail in issue 43. The problem is a bug in the code that some #include are wrong for all the Lite shaders but only for the ForwardAdd pass not for ForwardBase. I believe it shows these weird effects when lighting passes disagree.

@SonyUSA cool trick because of how the outline is rendered on the back faces.

**Comment by TCL987** [comment] 2018-07-20 06:33
This should be fixed in Version 0.25.

**Closed** 2018-07-20 06:33 UTC
